development:
  adapter:  postgresql
  database: geocoder_development
  pool: 5
  timeout: 5000
  username: admin
  password:
    
test:
  adapter:  postgresql
  database:  geocoder_test
  pool: 5
  timeout: 5000
  username: admin
  password:

production:
  adapter:  postgresql
  database: geocoder_production
  pool: 5
  timeout: 5000
  username: admin
  password:
